<h2><?php echo $this->escapeHtml($this->category->name); ?></h2>
<div class="posts">
    <?php foreach($this->posts as $post): ?>
        <div class="post col-lg-4 col-md-4 col-xs-12">
    		<div class="post-content">
            	<div class="post-image"><img src="<?php echo($this->basePath() . '/img/' . $this->escapeHtml($post->image)); ?>" /></div>
            	<h3 class="post-title"><?php echo $this->escapeHtml($post->title); ?></h3>
            	<p class="post-ingredients"><?php echo $this->escapeHtml($post->ingredients); ?></p>
            	<p class="post-description"><?php echo $this->escapeHtml($post->description); ?></p>
            	<a href="javascript:void(0);" class="view-more" title="Voir la suite">Voir la suite de l'article...</a>
        	</div>
    	</div>
    <?php endforeach;?>
</div>