<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/fonts.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    </head>
    <body>
        <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <h1><a class="navbar-brand" href="<?php echo $this->url('home') ?>">La Cuisine des Rêves</a></h1>
                <ul class="sidebar-nav">
                    <li><a href="<?php echo $this->url('home') ?>" title="Page d'accueil">Accueil</a></li>
                    <li><a href="<?php echo $this->url('home') ?>" title="Page blog">Blog</a></li>
                    <li><a href="javascript:void(0);" title="Page shopping">Shop</a></li>
                    <li><a href="javascript:void(0);" title="Page contact">Contact</a></li>
                </ul>
            </div><!-- /#sidebar-wrapper -->

            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <?php echo $this->content; ?>
                </div> <!-- /container -->
            </div><!-- /#page-content-wrapper -->

        </div><!-- /#wrapper -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
