<?php
    $title = 'Ajouter un nouvel article';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('add_post'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id_post'));
    echo $this->formHidden($form->get('csrf'));
?>
    <table id="category_form">
        <tfoot>
            <tr>
                <td colspan="2">
                    <?php echo $this->formSubmit($form->get('submit'));?>
                </td>
              </tr>
        </tfoot>
        <tbody>
            <tr>
                <th><?php echo $this->formLabel($form->get('id_category'));?></th>
                <td>
                    <?php echo $this->formSelect($form->get('id_category'));?>
                    <?php echo $this->formElementErrors($form->get('id_category'), array('class' => 'error_list'));?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->formLabel($form->get('title'));?></th>
                <td>
                    <?php echo $this->formInput($form->get('title'));?>
                    <?php echo $this->formElementErrors($form->get('title'), array('class' => 'error_list'));?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->formLabel($form->get('image'));?></th>
                <td>
                    <?php echo $this->formFile($form->get('image'));?>
                    <?php echo $this->formElementErrors($form->get('image'), array('class' => 'error_list'));?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->formLabel($form->get('ingredients'));?></th>
                <td>
                    <?php echo $this->formTextarea($form->get('ingredients'));?>
                    <?php echo $this->formElementErrors($form->get('ingredients'), array('class' => 'error_list'));?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->formLabel($form->get('description'));?></th>
                <td>
                    <?php echo $this->formTextarea($form->get('description'));?>
                    <?php echo $this->formElementErrors($form->get('description'), array('class' => 'error_list'));?>
                </td>
            </tr>
        </tbody>
    </table>
<?php
    echo $this->form()->closeTag();
?>